### ISSUE TITLE
Speed issues on Firefox

### ISSUE THREAD

**Issue by ExTechOp** [barrydegraaff/pgp-zimlet#101]
I just tried this on Firefox ESR 38.0.1 (under RHEL 6.6) against our Zimbra 8.6.0_GA_1169 (build 20150427101849). With my standard 4096 length GPG key I have to increase zimbraZimletUserProperties to 51200 as detailed in https://bugzilla.zimbra.com/show_bug.cgi?id=96823 — for some reason there is nothing in the zimlet documentation about this, though there used to be?

The zimlet does work, but is unusably slow when signing or encrypting. First, when I click OK on the zimlet popup, there is about 2 minutes of total browser unresponsiveness (no redraws or anything, I thought it had crashed). After that, it does another 2 minutes of work with a busy indicator. Top shows some system load, and Firefox running 100% CPU-bound.

I do see that you've documented 512 as a maximum usable key length for Firefox in the help file. Judging by my impromptu speed test, this seems accurate, but can you detail why this is — is the Chrome javascript engine simply four times as fast, or what?

(In case someone asks why a key length of 4096: because according to Lenstra & Verheul, 2048 is assumed to be safe against NSA-type intruders until 2020, and I work with the Finnish government with things that we'd prefer to stay just with us for more than five years)

**Comment by barrydegraaff** [comment]
zimbraZimletUserProperties, I have already removed it from the docu, filed a bug with zimbra, it is fixed in Zimbra 8.7

**Comment by barrydegraaff** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=96823

**Comment by ExTechOp** [comment]
I did say that :-)
It might be a good idea to include a bit about this limitation it in the documentation, until 8.7 comes out?

**Comment by barrydegraaff** [comment]
Firefox, while there is a performance improvement, I also filed multiple bugs on that:
https://github.com/openpgpjs/openpgpjs/issues/318

Also asked on the mailing list, problem FIREFOX IS DOG SLOW, only possible fixes are,
move crypto to server side or use a different browser.

**Comment by barrydegraaff** [comment]
I will remove the Firefox 512 recommendation from the documentation, as we have dropped support for generating these weak keys some time ago.

**Comment by barrydegraaff** [comment]
Also maybe you use a DSA key, those are A LOT slower, if it is an option (probably not), try to generate  a new key and test that.

About the you key-size, you probably had your key signed by others (web of trust) thats why it is not fitting in the 8.6 ldap.... since not many people have that problem. I have not documented anymore, because that scares other users..

**Comment by barrydegraaff** [comment]
Is there a change there is a difference in normal Firefox 38?

**Comment by barrydegraaff** [comment]
Please provide a link to your public key also

**Comment by ExTechOp** [comment]
Here's my public key at the MIT key server:
https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF032390FB3026172

**Comment by barrydegraaff** [comment]
Looked into your key, it appears to be 4096 RSA and has indeed a number of sub signatures. Nothing wrong with that!

I can't really do anything about the slowness, since it is an upstream problem (90% firefox and 10% openpgp) Also we already have A LOT of Firefox specific work-arounds in the openpgp codebase. (Making Firefox feel like the new Internet Explorer)

I can build the PGP stuff on the server-side, but right now, I don't have the time or donations to support that development. Happy to do it for a donation though. Thanks for your feedback!
