### ISSUE TITLE
Encrypting attachments with Zimbra 8.0.x

### ISSUE THREAD

**Issue by pwe123345** [barrydegraaff/pgp-zimlet#105]
Hello,

according to your documentation, there is a special pgp zimlet version for Zimbra 8.0.x (8.0.9 in my environment). With this zimlet it is not possible to encrypt attachments.

Should I try to install the newest release, even its only for Zimbra 8.5?

kind regards,
pwe

**Comment by barrydegraaff** [comment]
Hello Philipp,

No, please don't, as this will cripple your Zimbra.

Also attachment support according to standards will be in ZCS8.7. The current attachment support is hackish.

Barry

On Jul 16, 2015 8:09 AM, pwe123345 <notifications@github.com> wrote:
Hello,

according to your documentation, there is a special pgp zimlet version for Zimbra 8.0.x (8.0.9 in my environment). With this zimlet it is not possible to encrypt attachments.

Should I try to install the newest release, even its only for Zimbra 8.5?

kind regards,
Philipp Wehling

---
Reply to this email directly or view it on GitHub:
https://github.com/barrydegraaff/pgp-zimlet/issues/105

**Comment by pwe123345** [comment]
Hello,

thank you for your answer.

Do you have any information about Zimbra 8.7? As mentioned we are running 8.0.9, because 8.6 is buggy in a critical way (according to our sources).


kind regards,
pwe

**Comment by barrydegraaff** [comment]
I don't expect 8.7 in the next 3 months, but I am not Zimbra staff.

If you want to read attachments using PGP Zimlet, I can make a special branch and build that for you, if you are willing to donate some funds to the project.

Thanks Barry

On Jul 16, 2015 9:24 AM, pwe123345 <notifications@github.com> wrote:
Hello,

thank you for your answer.

Do you have any information about Zimbra 8.7? As mentioned we are running 8.0.9, because 8.6 is buggy in a critical way (according to our sources).


kind regards,
pwe

---

**Comment by pwe123345** [comment]
Hello,

thanks for your hint.

I will discuss it with my project manager and keep you informed.


kind regards,
pwe
