### ISSUE TITLE
Sent emails cannot be decrypted

### ISSUE THREAD

**Issue by rithiv** [barrydegraaff/pgp-zimlet#106]
This is likely expected behavior from a technical standpoint, but from a usability point of view it's annoying and regular users will probably not understand what's going on.

Issue:
Sent gpg encrypted email, try to read sent email, from Sent folder, get prompted with "Please provide private key and passphrase..."

Reproducable:
Always

See http://security.stackexchange.com/a/24631 for how Enigmail apparently handles this issue

**Comment by barrydegraaff** [comment]
Hi Tuan,

Can you implement a feature,   “Encrypt to self” (option in the manage keys window), which is on by default. With this preference turned on, all the emails a user encrypts are encrypted to the user himself as well as the recipients.

Let me know if you can find time for this, otherwise I will pick it up later.

Thanks and best regards, Barry

On Jul 29, 2015 3:24 PM, rithiv <notifications@github.com> wrote:
This is likely expected behavior from a technical standpoint, but from a usability point of view it's annoying and regular users will probably not understand what's going on.

Issue:
Sent gpg encrypted email, try to read sent email, from Sent folder, get prompted with "Please provide private key and passphrase..."

Reproducable:
Always

See http://security.stackexchange.com/a/24631 for how Enigmail apparently handles this issue

---
Reply to this email directly or view it on GitHub:
https://github.com/barrydegraaff/pgp-zimlet/issues/106

**Comment by tuanta** [comment]
@barrydegraaff we can use sender's public key to encrypt all encrypted emails (we can also have an option for people to set if you want that or not)
I can take this issue if you want. Sender public key is currently stored in "zimbra_openpgp_pubkeys1", right?

**Comment by barrydegraaff** [comment]
@tuanta exactly so it will do the same as selecting yourself in the encrypt window, as is also described in the help pages:

In the "Encrypt message" window:
- Select one or more recipients using (CTRL+click). You may wish to select yourself so you can read the message afterwards.

So when the new 'Always encrypt to self' option is set in Manage Keys window, the encrypted message is ALWAYS *ALSO* encrypted to the zimbra_openpgp_pubkeys1 (the users key).

Be careful with combining the arrays (objects) that hold pubkeys as they are a bit tricky.


Thanks a lot, looking forward to your PR!!
Barry

**Comment by tuanta** [comment]
@barrydegraaff: I have just been back from a business trip. I will start working on this issue by this weekend.

**Comment by barrydegraaff** [comment]
Thanks!

**Comment by barrydegraaff** [comment]
fixed in https://github.com/barrydegraaff/pgp-zimlet/commit/0584398be68b07e4befa71ae3b80ff4e80fc9c74
