### ISSUE TITLE
Problem with mail signing

### ISSUE THREAD

**Issue by tuanta** [barrydegraaff/pgp-zimlet#53]
Sign functions work incorrectly.

I tried to send a signed message to myself. Both messages in Sent and Inbox could be not verified.
It shows "Got a BAD signature".
It's too late today (almost midnight here). I will look into the code tomorrow morning.

**Comment by tuanta** [comment]
I think the problem is with sign function since I can still verify signature in some of my old messages.

**Comment by barrydegraaff** [comment]
The server needs a minute or two to sync after changes in the address book... Then it should work.

--- Original Message ---

**Comment by barrydegraaff** [comment]
Wait two minutes and try again

--- Original Message ---

**Comment by barrydegraaff** [comment]
Need to add a message "Address book sync in progress..." when the Zimlet is still waiting to become in sync with address book.

**Comment by barrydegraaff** [comment]
For anyone else who is reading this issue, the issue reported is in the development version. The version in the readme and on zimbra gallery is not affected.

**Comment by tuanta** [comment]
I just retried another test. The problem is still there.

**Comment by barrydegraaff** [comment]
I temporary disabled the contacts/addressbook feature, should have known better then devel 2 hours before short-break.

This should give all the funtionality back, without the addressbook, will ask you for new testing once the devel is done.
https://github.com/barrydegraaff/pgp-zimlet/commit/34bb4b77ba39e2935c55deb7ee1f31e3cc0ee6d9

**Comment by tuanta** [comment]
I found this problem caused by auto insert signature function.
When I change my preferences not to include signature when composing, it works fine.
It is a bit inconvenience for users and may need be improved. However, it is not urgent.

**Comment by barrydegraaff** [comment]
Thanks for this info I will commit a new version on Monday.

--- Original Message ---

**Comment by barrydegraaff** [comment]
I would like to ask you to test the latest development version of Zimbra OpenPGP Zimlet,(since you reported issues in the last version)
Truong Anh Tuan from iwayvietnam found that the issues using the compose windowintegration had to do with the Zimbra email signatures (not to be confused with PGP signatures) feature. If a user has html signatures configured for his/her account this will result in the errors you reported.
So far I have not found a good solution for this bug, other then prompting the user to temporary disable the signature.

Please test/deploy the attached zip, it should prompt a user to disable `html signature` if the userhad one.
Your result should at least always be a valid PGP message.

Thanks a lot,


Barry
 		 	   		  =

**Comment by barrydegraaff** [comment]
The bug with the Zimbra Mail Signatures is caused by:
controller._setFormat(Dwt.TEXT);
In the Zimlet code, if a user has no HTML formatted Signatures (not to be confused with PGP signatures) the switch to Dwt.TEXT goes without problems.

But if a HTML signature is inserted by Zimbra, `controller` also detects the change to TEXT mode, trowing a message to the end-user and then it all goes bad.

Possible solutions:
1. Automatically call 'Do Not Attach Signature'   but right now do not understand the implementation of this in Zimbra
2. Add a TEXT_PLAIN signature and apply it to the message source, some hints here http://www.zimbrafr.org/forum/topic/4247-zimlet-creation-signature/   but right now cannot add a signature to the current open message (not documented by Zimbra?)
3. Add a mime type to Zimbra (following RFC) and put the PGP data there, no longer use TEXT_PLAIN for that, will solve the issue
4. Another option??
5. Annoy end users with a message saying to disable Email Signatures, right now implemented pending someone finding out option 1-4?

**Comment by barrydegraaff** [comment]
Brent Dalley of BlueByte Solutions reconfirmed some issues in the zip file I send in my last mail.Also the same issues where previously reported by Bart van Lente of Yourhosting.
I fixed the broken forwarded/replied messages, by only enabling  the compose window integrationfor new messages. The forward/reply would have been nice, but the code was not intendedfor this purpose.
Please test the latest version from https://gallery.zimbra.com/type/zimlet/zimbra-openpgp-zimletif you have the time, your feedback is again much appreciated.
I rather drop features that do not work properly, then letting them in buggy.
Barry 		 	   		  =

**Comment by geje2005** [comment]
I am getting OpenPGP: Got a BAD signature mark in red colour. How did i resolve it

**Comment by barrydegraaff** [comment]
@geje2005 to get rid of the bac signature, you must import the senders correct public key. As soon as you have the senders public key installed and the message is not altered, the message goes away.
