### ISSUE TITLE
New public key is not available right after putting into a contact

### ISSUE THREAD

**Issue by tuanta** [barrydegraaff/pgp-zimlet#60]
New public key is not available right after putting into a contact.
Users need to reload browsers.

**Comment by barrydegraaff** [comment]
Looking into the contacts scanning code, we may wish to remove
parseContacts , readAddressBook, loadAllContacts, _waitForContactToLoadAndProcess 

And use a single ajax call to:
https://server.domain/home/usernmame/Contacts?fmt=txt&charset=UTF-8
And parse the result of that, this may be a lot faster, and more reliable.

**Comment by barrydegraaff** [comment]
It looks like sometimes the Zimbra backend can be slow to actually safe the contacts, then it won't work.

Tuan can you test the latest version based on : https://github.com/barrydegraaff/pgp-zimlet/commit/03f89a2e6d2f72232904bb427dce724e85a9a3b0

It is a huge performance improvement here, if still keys don't show up, we can call the readAddressBook function more ofter, since it is now much faster, it can be called each time when a verify is done or a select list is displayed to the end-user.

For performance reasons (on the server) I am not (yet) doing this now, pending on your test results.

Since this impacts ALL of the functionality of the Zimlet, can you do rigorous testing (all the test script and more)

And tell me if this version is an improvement.


Thanks Barry

**Comment by tuanta** [comment]
It is ok when I try to open a Encrypt dialog. I will do re-test all test cases.
And yes, it is much faster now.

**Comment by barrydegraaff** [comment]
released fix in 1.5.3
